### ISSUE TITLE
Break out host/port/username configurations

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-postgres#30] opened 2023-02-01 16:36 UTC

**Comment by qbatten** [comment] 2023-02-07 03:03
Dupe of #5, I think. I can push a PR for this if I get a ruling on whether we should 
- allow *either* sqlalchemy_url or host/port/etc
- switch over only to host/port/etc and drop sqlalchemy_url altogether

I don't care either way. Here's a repost of my comment on 5:

> Per @/aaronsteers [comment here](https://github.com/MeltanoLabs/tap-postgres/pull/19#discussion_r1090094581), should we drop the sqlalchemy_url option altogether? @/visch what do you think about that? Seems like the pro/con of allowing users to pass sqlalchemy_url is something like:

> Pro: Flexible for users
> Con: Leaves the tap with less control; could cause things to break if the tap upgrades driver and a user isn't aware of that

> Sounds like either way we'll exclude the dialect+driver option in the broken-out configuration.

**Closed** 2023-06-23 14:43 UTC
